# Generated by Django 5.2.2 on 2025-10-07 13:34

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomina', '0004_alter_empleado_sueldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSobretiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('factor', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'verbose_name': 'Tipo de Sobretiempo',
                'verbose_name_plural': 'Tipos de Sobretiempo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Sobretiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('numero_horas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sobretiempos', to='nomina.empleado')),
                ('tipo_sobretiempo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sobretiempos.tiposobretiempo')),
            ],
            options={
                'verbose_name': 'Sobretiempo',
                'verbose_name_plural': 'Sobretiempos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
