# Generated by Django 5.2.2 on 2025-09-22 03:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'La cédula debe tener 10 dígitos')])),
                ('nombre', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s]+$', 'El nombre solo puede contener letras y espacios')])),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departamento', models.CharField(choices=[('Ventas', 'Ventas'), ('Recursos Humanos', 'Recursos Humanos'), ('Marketing', 'Marketing'), ('Contabilidad', 'Contabilidad'), ('Tecnología', 'Tecnología')], max_length=50)),
                ('cargo', models.CharField(choices=[('Gerente', 'Gerente'), ('Analista', 'Analista'), ('Asistente', 'Asistente'), ('Especialista', 'Especialista'), ('Desarrollador', 'Desarrollador')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aniomes', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Formato válido: AAAAMM')])),
                ('ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iess', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('neto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='NominaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bono', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iess', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prestamo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('neto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.empleado')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='nomina.nomina')),
            ],
        ),
    ]
