# Generated by Django 5.2.2 on 2025-09-22 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomina',
            old_name='descuentos',
            new_name='tot_des',
        ),
        migrations.RenameField(
            model_name='nomina',
            old_name='iess',
            new_name='tot_ing',
        ),
        migrations.RenameField(
            model_name='nominadetalle',
            old_name='descuentos',
            new_name='tot_des',
        ),
        migrations.RenameField(
            model_name='nominadetalle',
            old_name='ingresos',
            new_name='tot_ing',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='ingresos',
        ),
    ]
