# Generated by Django 5.2.2 on 2025-10-06 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0002_rename_descuentos_nomina_tot_des_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominadetalle',
            name='bono',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='nominadetalle',
            name='prestamo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='nominadetalle',
            name='sueldo',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
