# Generated by Django 5.2.2 on 2025-10-07 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0003_alter_nominadetalle_bono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='sueldo',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
